apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: app
  name: message-service-deployment
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: message-service
  template:
    metadata:
      labels:
        app: message-service
    spec:
      containers:
      - name: message-service
        image: your-repo/message-service:latest
        imagePullPolicy: Always
        command: ["gunicorn"]
        args: ["--worker-class", "gevent", "--workers", "3", "--bind", "0.0.0.0:8000", "message_api.wsgi:application"]
        env:
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: database_details
                key: database_name
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database_details
                key: database_name
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: database_details
                key: database_name
        resources:
          # These has to be decided upon the actual usage and limit
          requests:
            cpu: "100m"
            memory: "200Mi"
          limits:
            cpu: "500m"
            memory: "500Mi"
        ports:
        - containerPort: 8000
      nodeSelector: 
        app: general
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: logging
  labels:
    app: fluentd
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '24231'
    spec:
      serviceAccountName: s3-access
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        image: 961328178101.dkr.ecr.ap-south-1.amazonaws.com/fluentd:1.1
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 200m
            memory: 1.5G
          requests:
            cpu: 100m
            memory: 400Mi
        env:
          - name: AWS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-credentials
                key: aws_key_id
          - name: AWS_SEC_KEY
            valueFrom:
              secretKeyRef:
                name: aws-credentials
                key: aws_sec_key
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluentd-config-volume
          mountPath: /fluentd/etc
      terminationGracePeriodSeconds: 30
      nodeSelector: 
        app: general
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluentd-config-volume
        configMap:
          name: fluentd-config
