apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-service-deployment
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  selector:
    matchLabels:
      app: message-service
  template:
    metadata:
      labels:
        app: message-service
    spec:
      containers:
      - name: message-service
        image: your-repo/message-service:latest
        command: ["gunicorn"]
        args: ["--worker-class", "gevent", "--workers", "3", "--bind", "0.0.0.0:8000", "message_api.wsgi:application"]
        env:
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: database_details
                key: database_name
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database_details
                key: database_name
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: database_details
                key: database_name
        resources:
          # These has to be decided upon the actual usage and limit
          requests:
            cpu: "100m"
            memory: "200Mi"
          limits:
            cpu: "500m"
            memory: "500Mi"
        ports:
        - containerPort: 8000
      - name: fluentd
        image: fluent/fluentd:latest
        # These has to be decided upon the actual usage and limit
        resources:
          requests:
            cpu: "100m"
            memory: "200Mi"
          limits:
            cpu: "500m"
            memory: "500Mi"
        env:
          - name: AWS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-credentials
                key: aws_key_id
          - name: AWS_SEC_KEY
            valueFrom:
              secretKeyRef:
                name: aws-credentials
                key: aws_sec_key
      serviceAccountName: "s3-access"
      nodeSelector: 
        app: "general"
      volumeMounts:
      - name: fluentd-config-volume
        mountPath: /fluentd/etc
    volumes:
    - name: fluentd-config-volume
      configMap:
        name: fluentd-config
