apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: s3-access-role
rules:
- apiGroups: [""]
  resources: ["s3buckets"]
  verbs: ["get", "list", "put"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: s3-access
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: s3-access-rolebinding
subjects:
- kind: ServiceAccount
  name: s3-access
  namespace: default
roleRef:
  kind: ClusterRole
  name: s3-access-role
  apiGroup: rbac.authorization.k8s.io
