apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: django-service-monitor
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: message-service  
  endpoints:
  - port: http  
    interval: 30s
    path: /metrics
